- hosts: localhost
  connection: local
  roles:
          - pihole
  vars_prompt:
          - name: "pihole_username"
            prompt: "Enter your system username"
            private: no
          - name: "pihole_user_real_name"
            prompt: "Enter your First and Last name"
            private: no
          - name: "pihole_user_email"
            prompt: "Enter your email address"
            private: no
