- hosts: localhost
  connection: local
  roles:
          - pihole
  vars_prompt:
          - name: "pihole_username"
            prompt: "Enter your system username"
            private: no
          - name: "git_user_real_name"
            prompt: "Enter your First and Last name for github"
            private: no
          - name: "git_user_email"
            prompt: "Enter your email address for github"
            private: no
