---
- name: install git
  action: >
          {{ ansible_pkg_mgr }} name=git state=present update_cache=yes

- name: configure git name
  git_config: name=user.name value="{{ git_user_real_name }}" scope=global
  become: yes
  become_user: "{{ system_username }}"

- name: configure git email
  git_config: name=user.email value="{{ git_user_email }}" scope=global
  become: yes
  become_user: "{{ system_username }}"

- name: create global gitignore file
  file: path=/home/{{ system_username }}/.gitignore state=touch owner={{ system_username }}
  become: yes
  become_user: "{{ system_username }}"

- name: configure global gitignore location
  git_config: name=core.excludefiles value="~/.gitignore" scope=global
  become: yes
  become_user: "{{ system_username }}"

- name: configure global gitignore
  lineinfile: path=/home/{{ system_username }}/.gitignore line={{ item }}
  with_items:
          - "*.swp"
          - "*.swo"
          - ".envrc"
  become: yes
  become_user: "{{ system_username }}"
